# Generated by Django 2.2 on 2021-02-08 20:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_site_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField(max_length=10)),
                ('description', models.TextField(blank=True, null=True, unique=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers_site_api.Course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(max_length=4)),
                ('question', models.CharField(max_length=300, unique=True)),
                ('number_correct_answers', models.IntegerField()),
                ('number_bad_answers', models.IntegerField()),
                ('score', models.IntegerField(default=1)),
                ('all_correctanswers', models.CharField(max_length=300, unique=True)),
                ('all_badanswers', models.CharField(max_length=300, unique=True)),
                ('list_of_choices', models.CharField(max_length=300, unique=True)),
                ('type_question', models.CharField(choices=[('BOOLEAN', 'Boolean'), ('MULTIPLECHOICE1', 'Multiple choice where only one answer is correct'), ('MULTIPLECHOICE2', 'Multiple choice where more than one answer is correct'), ('MULTIPLECHOICE3', 'Multiple choice where more than one answer is correct and all of them must be answered correctly')], default='BOOLEAN', max_length=120)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='teachers_site_api.Lesson')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('order', 'lesson')},
            },
        ),
        migrations.RemoveField(
            model_name='createcourse',
            name='name_class',
        ),
        migrations.RemoveField(
            model_name='createlesson',
            name='course',
        ),
        migrations.RemoveField(
            model_name='createquestion',
            name='lesson',
        ),
        migrations.DeleteModel(
            name='CreateClass',
        ),
        migrations.DeleteModel(
            name='CreateCourse',
        ),
        migrations.DeleteModel(
            name='CreateLesson',
        ),
        migrations.DeleteModel(
            name='CreateQuestion',
        ),
    ]
