# Generated by Django 2.2 on 2021-02-13 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_site_api', '0002_auto_20210213_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='name',
            new_name='the_question_is',
        ),
    ]
