# Generated by Django 2.2 on 2021-02-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_site_api', '0002_auto_20210208_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.IntegerField(),
        ),
    ]
