# Generated by Django 2.2 on 2021-01-30 07:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend_test_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='CreateCourse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('level', models.IntegerField(max_length=1)),
                ('name_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_test_api.CreateClass')),
            ],
        ),
        migrations.CreateModel(
            name='CreateLesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('level', models.IntegerField(max_length=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_test_api.CreateCourse')),
            ],
        ),
        migrations.CreateModel(
            name='CreateQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=300, unique=True)),
                ('level', models.IntegerField(max_length=1)),
                ('number_correct_answers', models.IntegerField(max_length=1)),
                ('number_bad_answers', models.IntegerField(max_length=1)),
                ('all_correctanswers', models.CharField(max_length=300, unique=True)),
                ('all_badanswers', models.CharField(max_length=300, unique=True)),
                ('list_of_choices', models.CharField(max_length=300, unique=True)),
                ('type_question', models.CharField(choices=[('BOOLEAN', 'Boolean'), ('MULTIPLECHOICE1', 'Multiple choice where only one answer is correct'), ('MULTIPLECHOICE2', 'Multiple choice where more than one answer is correct'), ('MULTIPLECHOICE3', 'Multiple choice where more than one answer is correct and all of them must be answered correctly')], default='BOOLEAN', max_length=120)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_test_api.CreateLesson')),
            ],
        ),
    ]
