# Generated by Django 2.2 on 2021-01-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_test_api', '0002_createclass_createcourse_createlesson_createquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createcourse',
            name='level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='createlesson',
            name='level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='createquestion',
            name='level',
            field=models.IntegerField(),
        ),
    ]
