# Generated by Django 2.2 on 2021-01-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_test_api', '0003_auto_20210130_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createquestion',
            name='number_bad_answers',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='createquestion',
            name='number_correct_answers',
            field=models.IntegerField(),
        ),
    ]
