# Generated by Django 2.2 on 2021-01-30 15:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend_test_api', '0004_auto_20210130_0714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='createquestion',
            options={'ordering': ['uploaded']},
        ),
        migrations.AddField(
            model_name='createquestion',
            name='uploaded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
