# Generated by Django 2.2 on 2021-02-03 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_test_api', '0005_auto_20210130_1520'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
