# Generated by Django 2.2 on 2021-02-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_manage_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_student',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
