# Generated by Django 2.2 on 2021-02-13 20:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudenProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='LessonAchivment',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('grade', models.FloatField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lessons', to='students_site_api.StudenProgress')),
            ],
        ),
        migrations.CreateModel(
            name='CourseAchivment',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('grade', models.FloatField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Courses', to='students_site_api.StudenProgress')),
            ],
        ),
    ]
